<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="sampleImages\4.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControls" Version="3.5.3" />
    <PackageReference Include="NetCore5.0.Microsoft.Expression.Drawing" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sampleImages\4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
